import { NextResponse } from 'next/server';
import { mkdtempSync, writeFileSync, rmSync } from 'node:fs';
import { execFileSync } from 'node:child_process';
import { tmpdir } from 'node:os'; import path from 'node:path';
export const runtime='nodejs';
const decode=(s:string)=>s.replace(/&amp;/g,'&').replace(/&lt;/g,'<').replace(/&gt;/g,'>').replace(/&#39;/g,"'").replace(/&quot;/g,'"');
function parseCsv(text:string){const lines=text.replace(/^\uFEFF/,'').split(/\r?\n/).filter(Boolean);return lines.map(line=>{const out:string[]=[];let cur='',quoted=false;for(let i=0;i<line.length;i++){const c=line[i];if(c==='"'){if(quoted&&line[i+1]==='"'){cur+='"';i++}else quoted=!quoted}else if((c===','||c===';'||c==='\t')&&!quoted){out.push(cur.trim());cur=''}else cur+=c}out.push(cur.trim());return out})}
function parseXlsx(file:string){const xml=(name:string)=>execFileSync('unzip',['-p',file,name],{encoding:'utf8'});let shared:string[]=[];try{shared=[...xml('xl/sharedStrings.xml').matchAll(/<si[^>]*>([\s\S]*?)<\/si>/g)].map(m=>decode([...m[1].matchAll(/<t[^>]*>([\s\S]*?)<\/t>/g)].map(x=>x[1]).join('')))}catch{}const sheet=xml('xl/worksheets/sheet1.xml');return [...sheet.matchAll(/<row[^>]*>([\s\S]*?)<\/row>/g)].map(row=>{const cells:string[]=[];for(const m of row[1].matchAll(/<c([^>]*)>([\s\S]*?)<\/c>/g)){const ref=m[1].match(/r="([A-Z]+)\d+"/)?.[1];if(!ref)continue;const type=m[1].match(/t="([^"]+)"/)?.[1];const col=ref.split('').reduce((n,c)=>n*26+c.charCodeAt(0)-64,0)-1;const raw=m[2].match(/<v>([\s\S]*?)<\/v>/)?.[1]??m[2].match(/<t[^>]*>([\s\S]*?)<\/t>/)?.[1]??'';cells[col]=type==='s'?shared[Number(raw)]??'':decode(raw)}return cells})}
export async function POST(req:Request){let dir='';try{const form=await req.formData();const f=form.get('file');if(!(f instanceof File))return NextResponse.json({error:'File tidak ditemukan.'},{status:400});const ext=f.name.split('.').pop()?.toLowerCase();dir=mkdtempSync(path.join(tmpdir(),'budget-'));const p=path.join(dir,f.name);writeFileSync(p,Buffer.from(await f.arrayBuffer()));let rows:string[][];if(ext==='xlsx')rows=parseXlsx(p);else if(ext==='csv'||ext==='xls')rows=parseCsv(Buffer.from(await f.arrayBuffer()).toString('utf8'));else return NextResponse.json({error:'Format harus .xlsx, .xls, atau .csv.'},{status:400});return NextResponse.json({rows})}catch(e){return NextResponse.json({error:`File tidak dapat dibaca. Untuk .xls lama, simpan ulang sebagai .xlsx atau CSV. ${e instanceof Error?e.message:''}`},{status:400})}finally{if(dir)rmSync(dir,{recursive:true,force:true})}}
