'use client';

import Image from 'next/image';
import { BarChart3, Bell, Building2, ChevronRight, ClipboardList, FileBarChart, FileSpreadsheet, Gauge, Home, LineChart as LineChartIcon, PieChart as PieChartIcon, Settings, Upload, WalletCards } from 'lucide-react';
import { Area, AreaChart, Bar, BarChart, CartesianGrid, Cell, Legend, Line, LineChart, Pie, PieChart, ResponsiveContainer, Tooltip, XAxis, YAxis } from 'recharts';
import { categories, departments, monthlyRealization, overBudgetDepartments, overBudgetValue, remainingBudget, requests, rupiah, totalActual, totalBudget, usagePercent } from '@/lib/budget-data';

const menu = [
  ['Dashboard', Home], ['Budget Planning', WalletCards], ['Budget vs Actual', BarChart3], ['Realisasi Budget', Gauge], ['Monitoring Budget', ClipboardList], ['Pengajuan Budget', FileSpreadsheet], ['Analisis Variance', LineChartIcon], ['Laporan Budget', FileBarChart], ['Upload Excel', Upload], ['Master Data', Building2], ['Pengaturan', Settings],
] as const;
const palette = ['#d4af37', '#f6d365', '#b88a16', '#fff2a8', '#8f6b12', '#5b4308'];

function Card({ title, value, note }: { title: string; value: string; note: string }) {
  return <section className="rounded-2xl border border-gold-500/20 bg-zinc-950/80 p-5 shadow-2xl shadow-black/30"><p className="text-sm text-zinc-400">{title}</p><h3 className="mt-2 text-2xl font-bold text-white">{value}</h3><p className="mt-2 text-xs text-gold-300">{note}</p></section>;
}
function Panel({ title, children }: { title: string; children: React.ReactNode }) {
  return <section className="rounded-2xl border border-gold-500/20 bg-gradient-to-b from-zinc-950 to-black p-5"><div className="mb-4 flex items-center justify-between"><h2 className="text-lg font-semibold text-white">{title}</h2><ChevronRight className="h-5 w-5 text-gold-500" /></div>{children}</section>;
}
const shortRupiah = (v: number) => `${Math.round(v / 1000000000)}M`;

export default function DashboardApp() {
  return <div className="min-h-screen bg-[radial-gradient(circle_at_top_right,#3a2a08,transparent_35%),#070707] text-slate-100">
    <aside className="fixed inset-y-0 left-0 z-20 hidden w-72 border-r border-gold-500/20 bg-black/90 p-5 lg:block">
      <div className="mb-8 flex flex-col items-center pt-2 text-center">
        <Image src="/assets/lool-logo.svg" alt="LOOL" width={110} height={82} priority className="h-auto w-[110px] object-contain" />
        <p className="mt-2 max-w-full text-sm font-semibold leading-5 text-gold-500">Budgeting 1001 &amp; Maison Y</p>
      </div>
      <nav className="space-y-2">{menu.map(([label, Icon], index) => <a key={label} href={`#${label.toLowerCase().replaceAll(' ', '-')}`} className={`flex items-center gap-3 rounded-xl px-4 py-3 text-sm transition hover:bg-gold-500/15 hover:text-gold-100 ${index === 0 ? 'bg-gold-500 text-black font-semibold' : 'text-zinc-300'}`}><Icon className="h-5 w-5" />{label}</a>)}</nav>
    </aside>
    <main className="lg:pl-72">
      <header className="sticky top-0 z-10 border-b border-gold-500/10 bg-black/80 px-4 py-4 backdrop-blur md:px-8"><div className="flex flex-col gap-3 md:flex-row md:items-center md:justify-between"><div><p className="text-sm text-gold-300">Dashboard Budgeting</p><h1 className="text-2xl font-bold md:text-3xl">Executive Budget Control Center</h1></div><button type="button" className="flex w-fit items-center gap-2 rounded-full border border-gold-500/30 px-4 py-2 text-sm text-gold-100 hover:bg-gold-500/10"><Bell className="h-4 w-4" /> Notifikasi Aman</button></div></header>
      <div className="space-y-6 p-4 md:p-8">
        <section id="dashboard" className="grid gap-4 sm:grid-cols-2 xl:grid-cols-6"><Card title="Total Budget" value={rupiah.format(totalBudget)} note="Rencana tahunan" /><Card title="Total Actual" value={rupiah.format(totalActual)} note="Realisasi berjalan" /><Card title="Sisa Budget" value={rupiah.format(remainingBudget)} note="Masih tersedia" /><Card title="Persentase Pemakaian" value={`${usagePercent}%`} note="Sehat di bawah 90%" /><Card title="Nilai Over Budget" value={rupiah.format(overBudgetValue)} note="Perlu tindakan" /><Card title="Dept. Over Budget" value={`${overBudgetDepartments}`} note="Marketing & IT" /></section>
        <section className="grid gap-6 xl:grid-cols-2"><Panel title="Grafik Budget vs Actual"><div className="h-80"><ResponsiveContainer><BarChart data={departments}><CartesianGrid stroke="#27272a" /><XAxis dataKey="name" stroke="#d4af37" /><YAxis stroke="#a1a1aa" tickFormatter={shortRupiah} /><Tooltip formatter={(v) => rupiah.format(Number(v))} contentStyle={{ background: '#09090b', border: '1px solid #d4af37' }} /><Legend /><Bar dataKey="budget" fill="#d4af37" name="Budget" radius={[6,6,0,0]} /><Bar dataKey="actual" fill="#f6d365" name="Actual" radius={[6,6,0,0]} /></BarChart></ResponsiveContainer></div></Panel><Panel title="Grafik Realisasi per Bulan"><div className="h-80"><ResponsiveContainer><AreaChart data={monthlyRealization}><CartesianGrid stroke="#27272a" /><XAxis dataKey="month" stroke="#d4af37" /><YAxis stroke="#a1a1aa" tickFormatter={shortRupiah} /><Tooltip formatter={(v) => rupiah.format(Number(v))} contentStyle={{ background: '#09090b', border: '1px solid #d4af37' }} /><Area dataKey="actual" name="Actual" stroke="#d4af37" fill="#d4af37" fillOpacity={0.25} /></AreaChart></ResponsiveContainer></div></Panel></section>
        <section className="grid gap-6 xl:grid-cols-2"><Panel title="Grafik Budget per Departemen"><div className="h-80"><ResponsiveContainer><LineChart data={departments}><CartesianGrid stroke="#27272a" /><XAxis dataKey="name" stroke="#d4af37" /><YAxis stroke="#a1a1aa" tickFormatter={shortRupiah} /><Tooltip formatter={(v) => rupiah.format(Number(v))} contentStyle={{ background: '#09090b', border: '1px solid #d4af37' }} /><Line type="monotone" dataKey="budget" stroke="#f6d365" strokeWidth={3} name="Budget" /></LineChart></ResponsiveContainer></div></Panel><Panel title="Grafik Komposisi Kategori"><div className="h-80"><ResponsiveContainer><PieChart><Pie data={categories} dataKey="value" nameKey="name" innerRadius={70} outerRadius={115} paddingAngle={4}>{categories.map((entry, index) => <Cell key={entry.name} fill={palette[index % palette.length]} />)}</Pie><Tooltip formatter={(v) => rupiah.format(Number(v))} contentStyle={{ background: '#09090b', border: '1px solid #d4af37' }} /><Legend /></PieChart></ResponsiveContainer></div></Panel></section>
        <Panel title="Tabel Monitoring Budget"><div className="overflow-x-auto"><table className="w-full min-w-[760px] text-left text-sm"><thead className="text-gold-300"><tr className="border-b border-gold-500/20"><th className="py-3">Departemen</th><th>Budget</th><th>Actual</th><th>Sisa / Over</th><th>Status</th></tr></thead><tbody>{departments.map((item) => { const diff = item.budget - item.actual; return <tr key={item.name} className="border-b border-zinc-800"><td className="py-4 font-medium text-white">{item.name}</td><td>{rupiah.format(item.budget)}</td><td>{rupiah.format(item.actual)}</td><td className={diff < 0 ? 'text-red-300' : 'text-emerald-300'}>{rupiah.format(diff)}</td><td><span className={`rounded-full px-3 py-1 text-xs font-semibold ${diff < 0 ? 'bg-red-500/15 text-red-200' : 'bg-emerald-500/15 text-emerald-200'}`}>{diff < 0 ? 'Over Budget' : 'On Track'}</span></td></tr>; })}</tbody></table></div></Panel>
        <section className="grid gap-6 xl:grid-cols-3">{menu.slice(1).map(([label], index) => <section id={label.toLowerCase().replaceAll(' ', '-')} key={label} className="rounded-2xl border border-gold-500/20 bg-zinc-950/70 p-5"><p className="text-xs uppercase tracking-[0.25em] text-gold-300">Menu</p><h2 className="mt-2 text-xl font-bold text-white">{label}</h2><p className="mt-3 text-sm leading-6 text-zinc-300">Halaman {label} menampilkan ringkasan dummy data budgeting, status pengajuan, kontrol monitoring, dan aksi aman tanpa koneksi database atau API eksternal.</p><button type="button" className="mt-4 rounded-lg bg-gold-500 px-4 py-2 text-sm font-semibold text-black hover:bg-gold-300">Lihat Detail</button>{index === 4 && <div className="mt-4 space-y-2">{requests.map((r) => <div key={r.id} className="rounded-lg border border-zinc-800 p-3 text-xs text-zinc-300"><b className="text-white">{r.id}</b> • {r.department} • {rupiah.format(r.amount)} • {r.status}</div>)}</div>}</section>)}</section>
      </div>
    </main>
  </div>;
}
